services:
  # Jaeger service
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"   # Jaeger thrift compact protocol used by the Jaeger agent
      - "6832:6832/udp"   # Jaeger thrift binary protocol used by the Jaeger agent
      - "5778:5778"       # Jaeger agent configs
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "14250:14250"     # Used by jaeger-collector to receive from jaeger-agent
      - "14268:14268"     # Can accept spans directly from clients in jaeger.thrift format
      - "14269:14269"     # Admin port
      - "9411:9411"       # Zipkin compatible endpoint
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16686"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s

  # Rust OpenTelemetry Application
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      jaeger:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_SERVICE_NAME=rust-otel-service
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge 